# Generated by Django 5.2.16 on 2026-07-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='refresh_jti',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
