# Generated by Django 4.2.30 on 2026-07-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_industrytype_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstype',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_types', to='organization.industrytype'),
        ),
        migrations.AddField(
            model_name='designation',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='organization.industrytype'),
        ),
    ]
