# Generated by Django 4.2.30 on 2026-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organizationbranch_and_membership_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='uniq_org_membership_org_profile',
        ),
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='uniq_org_membership_org_employee_code',
        ),
        migrations.RemoveIndex(
            model_name='organizationmembership',
            name='organizatio_organiz_3990b6_idx',
        ),
        migrations.RemoveField(
            model_name='organizationbranch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organizationbranch',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='organization',
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('branch', 'user_profile'), name='uniq_org_membership_branch_profile'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code', ''), _negated=True), fields=('branch', 'employee_code'), name='uniq_org_membership_branch_employee_code'),
        ),
    ]
