# Generated by Django 4.2.30 on 2026-07-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_lifecycle_config(apps, schema_editor):
    """Seed default statuses and transitions. Runtime code never hardcodes these edges."""
    Status = apps.get_model('organization', 'EmployeeLifecycleStatus')
    Transition = apps.get_model('organization', 'EmployeeLifecycleTransition')

    status_defs = [
        ('Draft', 'draft', 10, True, False),
        ('Onboarding Started', 'onboarding_started', 20, False, False),
        ('Active Employee', 'active', 30, False, False),
        ('Notice Period', 'notice_period', 40, False, False),
        ('Released', 'released', 50, False, False),
        ('Rehire', 'rehire', 60, False, False),
    ]
    by_key = {}
    for name, key, ordinal, is_initial, is_terminal in status_defs:
        by_key[key] = Status.objects.create(
            name=name,
            key=key,
            ordinal=ordinal,
            is_initial=is_initial,
            is_terminal=is_terminal,
            is_active=True,
        )

    transition_defs = [
        ('draft', 'onboarding_started', 'Start Onboarding', 10),
        ('onboarding_started', 'active', 'Activate', 10),
        ('active', 'notice_period', 'Start Notice', 10),
        ('notice_period', 'released', 'Release', 10),
        ('released', 'rehire', 'Rehire', 10),
        ('rehire', 'onboarding_started', 'Start Onboarding', 10),
    ]
    for from_key, to_key, action_label, sort_order in transition_defs:
        Transition.objects.create(
            from_status=by_key[from_key],
            to_status=by_key[to_key],
            action_label=action_label,
            sort_order=sort_order,
            is_active=True,
        )


def unseed_lifecycle_config(apps, schema_editor):
    Status = apps.get_model('organization', 'EmployeeLifecycleStatus')
    Transition = apps.get_model('organization', 'EmployeeLifecycleTransition')
    Transition.objects.all().delete()
    Status.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0012_org_scoped_department_and_attendance_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('access_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.accesstype')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.organizationbranch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.designation')),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.employeetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLifecycleStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('ordinal', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_initial', models.BooleanField(db_index=True, default=False)),
                ('is_terminal', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordinal', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLifecycleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_lifecycle_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_history', to='organization.employee')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_as_from', to='organization.employeelifecyclestatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_as_to', to='organization.employeelifecyclestatus')),
            ],
            options={
                'ordering': ['-changed_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='lifecycle_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.employeelifecyclestatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeLifecycleTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='organization.employeelifecyclestatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='organization.employeelifecyclestatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'action_label'],
                'indexes': [models.Index(fields=['from_status', 'is_active'], name='organizatio_from_st_733b2e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeelifecycletransition',
            constraint=models.UniqueConstraint(fields=('from_status', 'to_status'), name='uniq_lifecycle_transition_from_to'),
        ),
        migrations.AddIndex(
            model_name='employeelifecyclestatus',
            index=models.Index(fields=['is_active', 'ordinal'], name='organizatio_is_acti_c05240_idx'),
        ),
        migrations.AddIndex(
            model_name='employeelifecyclehistory',
            index=models.Index(fields=['employee', 'changed_at'], name='organizatio_employe_d8f57e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'lifecycle_status'], name='organizatio_organiz_5c48eb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_6451da_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code', ''), _negated=True), fields=('organization', 'employee_code'), name='uniq_employee_code_per_organization'),
        ),
        migrations.RunPython(seed_lifecycle_config, unseed_lifecycle_config),
    ]
