# Generated by Django 4.2.30 on 2026-07-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_employee_lifecycle_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeelifecyclehistory',
            options={'default_permissions': ('add', 'view', 'delete'), 'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='employeelifecyclehistory',
            name='from_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_as_from', to='organization.employeelifecyclestatus'),
        ),
        migrations.AlterField(
            model_name='employeelifecyclehistory',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_as_to', to='organization.employeelifecyclestatus'),
        ),
    ]
