# Generated by Django 4.2.30 on 2026-07-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0016_alter_designation_parent_alter_employee_access_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelifecyclehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_lifecycle_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
