# Generated by Django 4.2.30 on 2026-07-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0029_employee_document_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('uan_number', models.CharField(blank=True, max_length=30)),
                ('pf_number', models.CharField(blank=True, max_length=50)),
                ('esi_number', models.CharField(blank=True, max_length=50)),
                ('tax_regime', models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime')], default='new', max_length=20)),
                ('tax_identification_number', models.CharField(blank=True, help_text='TIN / SSN / National Tax ID based on country.', max_length=100)),
                ('is_pf_applicable', models.BooleanField(default=True)),
                ('is_esi_applicable', models.BooleanField(default=False)),
                ('professional_tax_applicable', models.BooleanField(default=False)),
                ('labour_welfare_fund_applicable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_detail', to='organization.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_tax_details',
            },
        ),
    ]
