# Generated by Django 4.2.30 on 2026-07-27 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0034_asset_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_policies', to='organization.employeetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_policies',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_entitlement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accrual_method', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('carry_forward_allowed', models.BooleanField(default=False)),
                ('carry_forward_limit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('encashment_allowed', models.BooleanField(default=False)),
                ('encashment_limit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allow_half_day', models.BooleanField(default=False)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('minimum_service_days', models.PositiveIntegerField(default=0)),
                ('maximum_consecutive_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_rules', to='organization.leavetype')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organization.leavepolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_policy_rules',
                'unique_together': {('policy', 'leave_type')},
            },
        ),
    ]
