# Generated by Django 4.2.30 on 2026-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_leave_policy_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavepolicyrule',
            name='accrual_method',
        ),
        migrations.RemoveField(
            model_name='leavepolicyrule',
            name='annual_entitlement',
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavepolicyrule',
            name='allocation_frequency',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='yearly', max_length=20),
        ),
        migrations.AddField(
            model_name='leavepolicyrule',
            name='allocation_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity allocated every allocation frequency.', max_digits=5),
        ),
        migrations.AddField(
            model_name='leavepolicyrule',
            name='annual_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum leave that can be allocated in a leave year.', max_digits=5),
        ),
    ]
