"""Organization URL routes."""

from django.urls import path

from apps.organization.views import (
    AccessTypeDetailView,
    AccessTypeListCreateView,
    BranchMembershipListView,
    CurrentOrganizationView,
    CurrentUserProfileView,
    DepartmentDetailView,
    DepartmentListCreateView,
    DesignationDetailView,
    DesignationListCreateView,
    DesignationMoveView,
    DesignationRepositionView,
    EmployeeDetailView,
    EmployeeLifecycleConfigView,
    EmployeeLifecycleTransitionView,
    EmployeeListCreateView,
    EmployeeTypeDetailView,
    EmployeeTypeListCreateView,
    HolidayCalendarDetailView,
    HolidayCalendarListCreateView,
    HolidayDetailView,
    HolidayListCreateView,
    IndustryTypeListView,
    LeaveTypeDetailView,
    LeaveTypeListCreateView,
    OrganizationCreateView,
    OrganizationSetupStatusView,
    ShiftDetailView,
    ShiftListCreateView,
    WorkWeekDetailView,
    WorkWeekListCreateView,
)

urlpatterns = [
    path('industry-types', IndustryTypeListView.as_view(), name='organization-industry-types'),
    path('setup-status', OrganizationSetupStatusView.as_view(), name='organization-setup-status'),
    path('create', OrganizationCreateView.as_view(), name='organization-create'),
    path('current', CurrentOrganizationView.as_view(), name='organization-current'),
    path('profile', CurrentUserProfileView.as_view(), name='organization-profile'),
    path('branches', BranchMembershipListView.as_view(), name='organization-branches'),
    path('departments', DepartmentListCreateView.as_view(), name='organization-departments'),
    path(
        'departments/<uuid:department_id>',
        DepartmentDetailView.as_view(),
        name='organization-department-detail',
    ),
    path(
        'departments/<uuid:department_id>/designations',
        DesignationListCreateView.as_view(),
        name='organization-designations',
    ),
    path(
        'designations/<uuid:designation_id>',
        DesignationDetailView.as_view(),
        name='organization-designation-detail',
    ),
    path(
        'designations/<uuid:designation_id>/move',
        DesignationMoveView.as_view(),
        name='organization-designation-move',
    ),
    path(
        'designations/<uuid:designation_id>/reposition',
        DesignationRepositionView.as_view(),
        name='organization-designation-reposition',
    ),
    path('employee-types', EmployeeTypeListCreateView.as_view(), name='organization-employee-types'),
    path(
        'employee-types/<uuid:item_id>',
        EmployeeTypeDetailView.as_view(),
        name='organization-employee-type-detail',
    ),
    path('access-types', AccessTypeListCreateView.as_view(), name='organization-access-types'),
    path(
        'access-types/<uuid:item_id>',
        AccessTypeDetailView.as_view(),
        name='organization-access-type-detail',
    ),
    path('shifts', ShiftListCreateView.as_view(), name='organization-shifts'),
    path('shifts/<uuid:item_id>', ShiftDetailView.as_view(), name='organization-shift-detail'),
    path('work-weeks', WorkWeekListCreateView.as_view(), name='organization-work-weeks'),
    path('work-weeks/<uuid:item_id>', WorkWeekDetailView.as_view(), name='organization-work-week-detail'),
    path('leave-types', LeaveTypeListCreateView.as_view(), name='organization-leave-types'),
    path('leave-types/<uuid:item_id>', LeaveTypeDetailView.as_view(), name='organization-leave-type-detail'),
    path('holiday-calendars', HolidayCalendarListCreateView.as_view(), name='organization-holiday-calendars'),
    path(
        'holiday-calendars/<uuid:item_id>',
        HolidayCalendarDetailView.as_view(),
        name='organization-holiday-calendar-detail',
    ),
    path(
        'holiday-calendars/<uuid:calendar_id>/holidays',
        HolidayListCreateView.as_view(),
        name='organization-holidays',
    ),
    path('holidays/<uuid:holiday_id>', HolidayDetailView.as_view(), name='organization-holiday-detail'),
    path('lifecycle', EmployeeLifecycleConfigView.as_view(), name='organization-lifecycle-config'),
    path('employees', EmployeeListCreateView.as_view(), name='organization-employees'),
    path('employees/<uuid:employee_id>', EmployeeDetailView.as_view(), name='organization-employee-detail'),
    path(
        'employees/<uuid:employee_id>/transition',
        EmployeeLifecycleTransitionView.as_view(),
        name='organization-employee-transition',
    ),
]
